# Do NOT update manually; changes here will be overwritten by Copier
_commit: v2.1.2
_src_path: gh:coopiteasy/oca-addons-repo-template
ci: GitHub
dependency_installation_mode: OCA
generate_requirements_txt: true
github_check_license: true
github_enable_codecov: true
github_enable_makepot: true
github_enable_stale_action: true
github_enforce_dev_status_compatibility: true
include_wkhtmltopdf: false
odoo_version: 14.0
org_name: Odoo Community Association (OCA)
org_slug: OCA
rebel_module_groups: []
repo_description: Custom modules for Coop IT Easy's clients.
repo_name: cie-custom
repo_slug: cie-custom
repo_website: https://github.com/OCA/cie-custom
travis_apt_packages: []
travis_apt_sources: []

