# Do NOT update manually; changes here will be overwritten by Copier
_commit: v1.5.1-12-g513f16d
_src_path: gh:coopiteasy/oca-addons-repo-template
ci: GitHub
dependency_installation_mode: OCA
generate_requirements_txt: true
include_wkhtmltopdf: false
odoo_version: 14.0
rebel_module_groups: []
repo_description: Custom modules for Coop IT Easy's clients.
repo_name: cie-custom
repo_slug: cie-custom
travis_apt_packages: []
travis_apt_sources: []
