{
    "name": "Dépendances UGESS",
    "version": "16.0.0.0.1",
    "author": "Akretion",  # pylint: disable=manifest-required-author
    "website": "https://coopiteasy.be",
    "license": "AGPL-3",
    "category": "Generic Modules",
    "depends": [
        # Odoo
        "point_of_sale",
        "pos_hr",
        "website",
        "purchase",
        "analytic",
        # OCA
        "account_financial_report",
        "auth_oidc",
        "barcodes_generator_product",
        "base_address_extended_geonames_import",
        "base_location_district",
        "base_optional_quick_create",
        "base_user_role",
        "bi_sql_editor",
        "bi_view_editor",
        "l10n_fr_pos_cert",
        "l10n_fr_pos_cert_update_draft_order_line",
        "membership_extension",
        "membership_variable_period",
        "membership_withdrawal",
        "password_security",
        "pos_customer_comment",
        "pos_discount_all",
        "pos_escpos_status",
        "pos_membership_extension",
        "pos_minimize_menu",
        "pos_order_new_line",
        "pos_order_reorder",
        "pos_order_to_sale_order",
        "pos_payment_change",
        "pos_payment_usability",
        "pos_payment_method_change_policy",
        "pos_receipt_usability",
        "product_category_type",
        "product_multi_barcode_constraint_per_company",
        "product_print_category",
        "sale_product_template_tags",
        "server_action_mass_edit",
        "stock_change_qty_reason",
        "web_environment_ribbon",
        "web_responsive",
        "web_theme_classic",
    ],
    "installable": True,
    "application": False,
}
