from . import test_export_security
from . import test_membership_security
from . import test_point_of_sale_security
from . import test_portal_share_security
from . import test_pos_loyalty_security
from . import test_product_security
from . import test_res_district_security
from . import test_res_partner_security
from . import test_stock_security
