{
    "name": "UGESS",
    "version": "16.0.0.0.1",
    "author": "Akretion",  # pylint: disable=manifest-required-author
    "website": "https://coopiteasy.be",
    "license": "AGPL-3",
    "category": "Generic Modules",
    "depends": [
        "ugess_base",
        "ugess_data",
        "ugess_membership",
        "ugess_membership_interview",
        "ugess_membership_reporting",
        "ugess_multicompany",
        "ugess_partner_household",
        "ugess_partner_revenue",
        "ugess_partner_social_project",
        "ugess_pos",
        "ugess_pricelist",
        "ugess_pricetag",
        "ugess_qvp",
        "ugess_sale_reporting",
        "ugess_stock",
        "ugess_stock_scrap",
        "ugess_supply_source",
        "ugess_uom",
        "ugess_views",
        "ugess_security",
        "ugess_security_user_stats",
    ],
    "installable": True,
    "application": False,
}
